.PHONY: all build test clean merge-header check-header refresh \
        build-config test-config test-merged-feature-flags \
        build-standard test-standard \
        build-logs-only test-logs-only \
        build-profiles-only test-profiles-only \
        build-traces-only test-traces-only \
        build-metrics-only test-metrics-only

CC ?= cc
CXX ?= c++
CPPFLAGS ?=
CFLAGS ?= -std=c11 -Wall -Wextra -Werror
CXXFLAGS ?= -std=c++14 -Wall -Wextra -Werror

BUILD_DIR := .build
INCLUDE_DIR := include/otlp_format
SPLIT_SOURCES := $(shell find $(INCLUDE_DIR) -type f | sort)
ROOT_HEADER := otlp_format_bundled.h
ROOT_CPP_HEADER := otlp_format_bundled.hpp
C_TEST_SRCS_LOCAL := tests/main.c tests/test_common.c tests/test_logs.c \
                     tests/test_traces.c tests/test_metrics.c tests/test_profiles.c
CPP_TEST_SRCS_LOCAL := tests/main.cpp tests/test_common.cpp tests/test_logs.cpp \
                       tests/test_traces.cpp tests/test_metrics.cpp tests/test_profiles.cpp
C_TEST_SRCS   := $(patsubst tests/%,$(BUILD_DIR)/tests/%,$(C_TEST_SRCS_LOCAL))
CPP_TEST_SRCS := $(patsubst tests/%,$(BUILD_DIR)/tests/%,$(CPP_TEST_SRCS_LOCAL))
TEST_HEADERS  := $(BUILD_DIR)/tests/test_helpers.h $(BUILD_DIR)/tests/test_helpers.hpp
C_TEST := $(BUILD_DIR)/test_otlp_format_c
CPP_TEST := $(BUILD_DIR)/test_otlp_format_cpp
DIRECT_C_SRC := $(BUILD_DIR)/test_direct_headers.c
DIRECT_CPP_SRC := $(BUILD_DIR)/test_direct_headers.cpp
DIRECT_C_TEST := $(BUILD_DIR)/test_direct_headers_c
DIRECT_CPP_TEST := $(BUILD_DIR)/test_direct_headers_cpp
# Standard-include variants (no generated header; resolves via -I)
STD_C_TEST := $(BUILD_DIR)/test_otlp_format_std_c
STD_CPP_TEST := $(BUILD_DIR)/test_otlp_format_std_cpp
ALL_SIGNALS := logs profiles traces metrics
SIGNALS ?= $(ALL_SIGNALS)
ALL_SIGNALS_CPPFLAGS := -DOTLP_FORMAT_ENABLE_LOGS=1 -DOTLP_FORMAT_ENABLE_PROFILES=1 -DOTLP_FORMAT_ENABLE_TRACES=1 -DOTLP_FORMAT_ENABLE_METRICS=1
LOGS_ONLY_CPPFLAGS := -DOTLP_FORMAT_ENABLE_LOGS=1
PROFILES_ONLY_CPPFLAGS := -DOTLP_FORMAT_ENABLE_PROFILES=1
TRACES_ONLY_CPPFLAGS := -DOTLP_FORMAT_ENABLE_TRACES=1
METRICS_ONLY_CPPFLAGS := -DOTLP_FORMAT_ENABLE_METRICS=1

define merge_header
	@set -eu; \
	output='$(1)'; \
	signals='$(strip $(2))'; \
	output_dir=$$(dirname -- "$$output"); \
	tmp_output="$$output.tmp"; \
	mkdir -p "$$output_dir"; \
	{ \
		printf '/* Generated from c/include/otlp_format/. Do not edit this file directly. */\n'; \
		printf '\n'; \
		printf '#ifndef OTLP_FORMAT_BUNDLED_H\n'; \
		printf '#define OTLP_FORMAT_BUNDLED_H\n'; \
		printf '\n'; \
		printf '\n'; \
		sed '/^#ifndef OTLP_FORMAT_COMMON_H$$/d; /^#define OTLP_FORMAT_COMMON_H$$/d; /^#endif \/\* OTLP_FORMAT_COMMON_H \*\/$$/d' $(INCLUDE_DIR)/common/common.h; \
		printf '\n'; \
		for signal in $$signals; do \
			case "$$signal" in \
				logs) \
					sed '/^#ifndef OTLP_FORMAT_LOGS_H$$/d; /^#define OTLP_FORMAT_LOGS_H$$/d; /^#include "\.\.\/common\/common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_LOGS_H \*\/$$/d' $(INCLUDE_DIR)/logs/logs.h; \
					;; \
				profiles) \
					sed '/^#ifndef OTLP_FORMAT_PROFILES_H$$/d; /^#define OTLP_FORMAT_PROFILES_H$$/d; /^#include "\.\.\/common\/common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_PROFILES_H \*\/$$/d' $(INCLUDE_DIR)/profiles/profiles.h; \
					;; \
				traces) \
					sed '/^#ifndef OTLP_FORMAT_TRACES_H$$/d; /^#define OTLP_FORMAT_TRACES_H$$/d; /^#include "\.\.\/common\/common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_TRACES_H \*\/$$/d' $(INCLUDE_DIR)/traces/traces.h; \
					;; \
				metrics) \
					sed '/^#ifndef OTLP_FORMAT_METRICS_H$$/d; /^#define OTLP_FORMAT_METRICS_H$$/d; /^#include "\.\.\/common\/common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_METRICS_H \*\/$$/d' $(INCLUDE_DIR)/metrics/metrics.h; \
					;; \
			esac; \
			printf '\n'; \
		done; \
		printf '#endif /* OTLP_FORMAT_BUNDLED_H */\n'; \
	} > "$$tmp_output"; \
	mv "$$tmp_output" "$$output"
endef

define merge_header_cpp
	@set -eu; \
	output='$(1)'; \
	signals='$(strip $(2))'; \
	output_dir=$$(dirname -- "$$output"); \
	tmp_output="$$output.tmp"; \
	mkdir -p "$$output_dir"; \
	{ \
		printf '/* Generated from c/include/otlp_format/. Do not edit this file directly. */\n'; \
		printf '\n'; \
		printf '#ifndef OTLP_FORMAT_BUNDLED_HPP\n'; \
		printf '#define OTLP_FORMAT_BUNDLED_HPP\n'; \
		printf '\n'; \
		printf '\n'; \
		sed '/^#ifndef OTLP_FORMAT_COMMON_H$$/d; /^#define OTLP_FORMAT_COMMON_H$$/d; /^#endif \/\* OTLP_FORMAT_COMMON_H \*\/$$/d' $(INCLUDE_DIR)/common/common.h; \
		printf '\n'; \
		for signal in $$signals; do \
			case "$$signal" in \
				logs) \
					sed '/^#ifndef OTLP_FORMAT_LOGS_H$$/d; /^#define OTLP_FORMAT_LOGS_H$$/d; /^#include "\.\.\/common\/common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_LOGS_H \*\/$$/d' $(INCLUDE_DIR)/logs/logs.h; \
					;; \
				profiles) \
					sed '/^#ifndef OTLP_FORMAT_PROFILES_H$$/d; /^#define OTLP_FORMAT_PROFILES_H$$/d; /^#include "\.\.\/common\/common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_PROFILES_H \*\/$$/d' $(INCLUDE_DIR)/profiles/profiles.h; \
					;; \
				traces) \
					sed '/^#ifndef OTLP_FORMAT_TRACES_H$$/d; /^#define OTLP_FORMAT_TRACES_H$$/d; /^#include "\.\.\/common\/common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_TRACES_H \*\/$$/d' $(INCLUDE_DIR)/traces/traces.h; \
					;; \
				metrics) \
					sed '/^#ifndef OTLP_FORMAT_METRICS_H$$/d; /^#define OTLP_FORMAT_METRICS_H$$/d; /^#include "\.\.\/common\/common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_METRICS_H \*\/$$/d' $(INCLUDE_DIR)/metrics/metrics.h; \
					;; \
			esac; \
			printf '\n'; \
		done; \
		printf '#ifdef __cplusplus\n'; \
		printf '\n'; \
		sed '/^#ifndef OTLP_FORMAT_COMMON_HPP$$/d; /^#define OTLP_FORMAT_COMMON_HPP$$/d; /^#include "common\.h"$$/d; /^#endif \/\* OTLP_FORMAT_COMMON_HPP \*\/$$/d' $(INCLUDE_DIR)/common/common.hpp; \
		printf '\n'; \
		for signal in $$signals; do \
			case "$$signal" in \
				logs) \
					sed '/^#ifndef OTLP_FORMAT_LOGS_HPP$$/d; /^#define OTLP_FORMAT_LOGS_HPP$$/d; /^#include "\.\.\/common\/common\.hpp"$$/d; /^#include "logs\.h"$$/d; /^#endif \/\* OTLP_FORMAT_LOGS_HPP \*\/$$/d' $(INCLUDE_DIR)/logs/logs.hpp; \
					;; \
				profiles) \
					sed '/^#ifndef OTLP_FORMAT_PROFILES_HPP$$/d; /^#define OTLP_FORMAT_PROFILES_HPP$$/d; /^#include "\.\.\/common\/common\.hpp"$$/d; /^#include "profiles\.h"$$/d; /^#endif \/\* OTLP_FORMAT_PROFILES_HPP \*\/$$/d' $(INCLUDE_DIR)/profiles/profiles.hpp; \
					;; \
				traces) \
					sed '/^#ifndef OTLP_FORMAT_TRACES_HPP$$/d; /^#define OTLP_FORMAT_TRACES_HPP$$/d; /^#include "\.\.\/common\/common\.hpp"$$/d; /^#include "traces\.h"$$/d; /^#endif \/\* OTLP_FORMAT_TRACES_HPP \*\/$$/d' $(INCLUDE_DIR)/traces/traces.hpp; \
					;; \
				metrics) \
					sed '/^#ifndef OTLP_FORMAT_METRICS_HPP$$/d; /^#define OTLP_FORMAT_METRICS_HPP$$/d; /^#include "\.\.\/common\/common\.hpp"$$/d; /^#include "metrics\.h"$$/d; /^#endif \/\* OTLP_FORMAT_METRICS_HPP \*\/$$/d' $(INCLUDE_DIR)/metrics/metrics.hpp; \
					;; \
			esac; \
			printf '\n'; \
		done; \
		printf '#endif\n'; \
		printf '\n'; \
		printf '#endif /* OTLP_FORMAT_BUNDLED_HPP */\n'; \
	} > "$$tmp_output"; \
	mv "$$tmp_output" "$$output"
endef

all: build

merge-header: $(ROOT_HEADER) $(ROOT_CPP_HEADER)

$(ROOT_HEADER): $(SPLIT_SOURCES)
	$(call merge_header,$@,$(ALL_SIGNALS))

$(ROOT_CPP_HEADER): $(SPLIT_SOURCES)
	$(call merge_header_cpp,$@,$(ALL_SIGNALS))

check-header: $(SPLIT_SOURCES) | $(BUILD_DIR)
	$(call merge_header,$(BUILD_DIR)/otlp_format.check.h,$(ALL_SIGNALS))
	@cmp -s $(ROOT_HEADER) $(BUILD_DIR)/otlp_format.check.h || { \
		echo "$(ROOT_HEADER) is out of date; run 'make merge-header' in c/"; \
		exit 1; \
	}
	$(call merge_header_cpp,$(BUILD_DIR)/otlp_format.check.hpp,$(ALL_SIGNALS))
	@cmp -s $(ROOT_CPP_HEADER) $(BUILD_DIR)/otlp_format.check.hpp || { \
		echo "$(ROOT_CPP_HEADER) is out of date; run 'make merge-header' in c/"; \
		exit 1; \
	}

refresh: merge-header test

build:
	$(MAKE) clean
	$(MAKE) build-config SIGNALS="$(ALL_SIGNALS)" CPPFLAGS="$(ALL_SIGNALS_CPPFLAGS)"
	$(MAKE) build-standard CPPFLAGS="$(ALL_SIGNALS_CPPFLAGS)"

build-config: $(C_TEST) $(CPP_TEST)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/tests/%: tests/% | $(BUILD_DIR)
	mkdir -p $(BUILD_DIR)/tests
	cp $< $@

# Merged-header build: test files in .build/tests/ find the root header via -I.
$(C_TEST): $(C_TEST_SRCS) $(TEST_HEADERS) $(ROOT_HEADER) | $(BUILD_DIR)
	$(CC) $(CPPFLAGS) $(CFLAGS) -I. -I$(BUILD_DIR)/tests -Itestdeps $(C_TEST_SRCS) -o $@

$(CPP_TEST): $(CPP_TEST_SRCS) $(TEST_HEADERS) $(ROOT_CPP_HEADER) | $(BUILD_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I. -I$(BUILD_DIR)/tests -Itestdeps $(CPP_TEST_SRCS) -o $@

# Standard-include build: test files in .build/tests/ have no local otlp_format.h,
# so #include "otlp_format.h" falls through to -I$(INCLUDE_DIR).
build-standard: $(STD_C_TEST) $(STD_CPP_TEST) $(DIRECT_C_TEST) $(DIRECT_CPP_TEST)

$(STD_C_TEST): $(C_TEST_SRCS) $(TEST_HEADERS) $(ROOT_HEADER) $(SPLIT_SOURCES) | $(BUILD_DIR)
	$(CC) $(CPPFLAGS) $(CFLAGS) -I. -I$(BUILD_DIR)/tests -Itestdeps -I$(INCLUDE_DIR) $(C_TEST_SRCS) -o $@

$(STD_CPP_TEST): $(CPP_TEST_SRCS) $(TEST_HEADERS) $(ROOT_CPP_HEADER) $(SPLIT_SOURCES) | $(BUILD_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I. -I$(BUILD_DIR)/tests -Itestdeps -I$(INCLUDE_DIR) $(CPP_TEST_SRCS) -o $@

$(DIRECT_C_SRC): | $(BUILD_DIR)
	printf '%s\n' '#include "common/common.h"' '#include "logs/logs.h"' '#include "profiles/profiles.h"' '#include "traces/traces.h"' '#include "metrics/metrics.h"' 'int main(void) { return 0; }' > $@

$(DIRECT_CPP_SRC): | $(BUILD_DIR)
	printf '%s\n' '#include "common/common.hpp"' '#include "logs/logs.hpp"' '#include "profiles/profiles.hpp"' '#include "traces/traces.hpp"' '#include "metrics/metrics.hpp"' 'int main() { return 0; }' > $@

$(DIRECT_C_TEST): $(DIRECT_C_SRC) $(SPLIT_SOURCES) | $(BUILD_DIR)
	$(CC) $(CPPFLAGS) $(CFLAGS) -I$(INCLUDE_DIR) $< -o $@

$(DIRECT_CPP_TEST): $(DIRECT_CPP_SRC) $(SPLIT_SOURCES) | $(BUILD_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I$(INCLUDE_DIR) $< -o $@

test:
	$(MAKE) clean
	$(MAKE) test-config SIGNALS="$(ALL_SIGNALS)" CPPFLAGS="$(ALL_SIGNALS_CPPFLAGS)"
	$(MAKE) test-standard CPPFLAGS="$(ALL_SIGNALS_CPPFLAGS)"
	$(MAKE) test-merged-feature-flags

test-config: build-config
	$(C_TEST)
	$(CPP_TEST)

test-standard: build-standard
	$(STD_C_TEST)
	$(STD_CPP_TEST)
	$(DIRECT_C_TEST)
	$(DIRECT_CPP_TEST)

test-merged-feature-flags: $(ROOT_HEADER) | $(BUILD_DIR)
	printf '%s\n' '#include "otlp_format_bundled.h"' '#ifndef OTLP_FORMAT_ENABLE_LOGS' '#error logs should be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_PROFILES' '#error profiles should not be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_TRACES' '#error traces should not be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_METRICS' '#error metrics should not be enabled' '#endif' 'int main(void) { return 0; }' > $(BUILD_DIR)/test_feature_flags_logs.c
	$(CC) $(CFLAGS) -I. -DOTLP_FORMAT_ENABLE_LOGS=1 $(BUILD_DIR)/test_feature_flags_logs.c -o $(BUILD_DIR)/test_feature_flags_logs
	$(BUILD_DIR)/test_feature_flags_logs
	printf '%s\n' '#include "otlp_format_bundled.h"' '#ifdef OTLP_FORMAT_ENABLE_LOGS' '#error logs should not be enabled' '#endif' '#ifndef OTLP_FORMAT_ENABLE_PROFILES' '#error profiles should be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_TRACES' '#error traces should not be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_METRICS' '#error metrics should not be enabled' '#endif' 'int main(void) { return 0; }' > $(BUILD_DIR)/test_feature_flags_profiles.c
	$(CC) $(CFLAGS) -I. -DOTLP_FORMAT_ENABLE_PROFILES=1 $(BUILD_DIR)/test_feature_flags_profiles.c -o $(BUILD_DIR)/test_feature_flags_profiles
	$(BUILD_DIR)/test_feature_flags_profiles
	printf '%s\n' '#include "otlp_format_bundled.h"' '#ifdef OTLP_FORMAT_ENABLE_LOGS' '#error logs should not be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_PROFILES' '#error profiles should not be enabled' '#endif' '#ifndef OTLP_FORMAT_ENABLE_TRACES' '#error traces should be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_METRICS' '#error metrics should not be enabled' '#endif' 'int main(void) { return 0; }' > $(BUILD_DIR)/test_feature_flags_traces.c
	$(CC) $(CFLAGS) -I. -DOTLP_FORMAT_ENABLE_TRACES=1 $(BUILD_DIR)/test_feature_flags_traces.c -o $(BUILD_DIR)/test_feature_flags_traces
	$(BUILD_DIR)/test_feature_flags_traces
	printf '%s\n' '#include "otlp_format_bundled.h"' '#ifdef OTLP_FORMAT_ENABLE_LOGS' '#error logs should not be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_PROFILES' '#error profiles should not be enabled' '#endif' '#ifdef OTLP_FORMAT_ENABLE_TRACES' '#error traces should not be enabled' '#endif' '#ifndef OTLP_FORMAT_ENABLE_METRICS' '#error metrics should be enabled' '#endif' 'int main(void) { return 0; }' > $(BUILD_DIR)/test_feature_flags_metrics.c
	$(CC) $(CFLAGS) -I. -DOTLP_FORMAT_ENABLE_METRICS=1 $(BUILD_DIR)/test_feature_flags_metrics.c -o $(BUILD_DIR)/test_feature_flags_metrics
	$(BUILD_DIR)/test_feature_flags_metrics

build-logs-only:
	$(MAKE) clean
	$(MAKE) build-config SIGNALS="logs" CPPFLAGS="$(LOGS_ONLY_CPPFLAGS)"

test-logs-only:
	$(MAKE) clean
	$(MAKE) test-config SIGNALS="logs" CPPFLAGS="$(LOGS_ONLY_CPPFLAGS)"
	$(MAKE) test-standard CPPFLAGS="$(LOGS_ONLY_CPPFLAGS)"

build-profiles-only:
	$(MAKE) clean
	$(MAKE) build-config SIGNALS="profiles" CPPFLAGS="$(PROFILES_ONLY_CPPFLAGS)"

test-profiles-only:
	$(MAKE) clean
	$(MAKE) test-config SIGNALS="profiles" CPPFLAGS="$(PROFILES_ONLY_CPPFLAGS)"
	$(MAKE) test-standard CPPFLAGS="$(PROFILES_ONLY_CPPFLAGS)"

build-traces-only:
	$(MAKE) clean
	$(MAKE) build-config SIGNALS="traces" CPPFLAGS="$(TRACES_ONLY_CPPFLAGS)"

test-traces-only:
	$(MAKE) clean
	$(MAKE) test-config SIGNALS="traces" CPPFLAGS="$(TRACES_ONLY_CPPFLAGS)"
	$(MAKE) test-standard CPPFLAGS="$(TRACES_ONLY_CPPFLAGS)"

build-metrics-only:
	$(MAKE) clean
	$(MAKE) build-config SIGNALS="metrics" CPPFLAGS="$(METRICS_ONLY_CPPFLAGS)"

test-metrics-only:
	$(MAKE) clean
	$(MAKE) test-config SIGNALS="metrics" CPPFLAGS="$(METRICS_ONLY_CPPFLAGS)"
	$(MAKE) test-standard CPPFLAGS="$(METRICS_ONLY_CPPFLAGS)"

clean:
	rm -rf $(BUILD_DIR)